###
# MCPのinitialize
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Authorization: SuperUser:SYS

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-03-26",
    "capabilities": {},
    "clientInfo": {
      "name": "vscode-rest-client",
      "version": "0.1.0"
    }
  }
}


###
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 433c2578-4819-430a-b89f-422fee745373
Authorization: SuperUser:SYS

{
  "jsonrpc": "2.0",
  "method": "notifications/initialized",
  "params": {}
}


###
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 433c2578-4819-430a-b89f-422fee745373
Authorization: SuperUser:SYS

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}

### Obtain the contact information for the sales representative at the client company
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 433c2578-4819-430a-b89f-422fee745373
Authorization: SuperUser:SYS

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetAccountOwner",
    "arguments": {
      "custid": "C001"
    }
  }
}
