###
# MCPのinitialize
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-03-26",
    "capabilities": {},
    "clientInfo": {
      "name": "vscode-rest-client",
      "version": "0.1.0"
    }
  }
}


###
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 8212922d-8b75-4470-a519-fe827413308e

{
  "jsonrpc": "2.0",
  "method": "notifications/initialized",
  "params": {}
}


###
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}

### Obtain the contact information for the sales representative at the client company
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetAccountOwner",
    "arguments": {
      "custid": "C001"
    }
  }
}

### Retrieve Contact Information for a Business Partner Based on the Business Partner ID
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetCustomerContacts",
    "arguments": {
      "custid": "C001"
    }
  }
}

###  Retrieve customer company information based on the customer ID (customer_id) (similar to the information in the CRM)
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetCustomerInfo",
    "arguments": {
      "custid": "C001"
    }
  }
}


### Retrieve past inquiry ticket information based on the client company ID
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetSupportTicket",
    "arguments": {
      "custid": "C001"
    }
  }
}

### Retrieve Meeting Minutes Using a Business Partner's ID
POST http://localhost:51504/mcp
Accept: application/json, text/event-stream
Content-Type: application/json;charset=utf-8
Mcp-Session-Id: 71b1bdb8-43a9-4a6b-96f2-d5fc3ed669fc

{
  "jsonrpc": "2.0",
  "id": 4,
  "method": "tools/call",
  "params": {
    "name": "mcp_meetingservice_GetMeetingMinutes",
    "arguments": {
      "custid": "C001"
    }
  }
}
